=== AncorGG/Twitch_Assignment/twitch.dtd
<!ELEMENT twitch (streams)>
<!ATTLIST twitch xmlns:stm CDATA #REQUIRED>
<!ATTLIST twitch xmlns:usr CDATA #REQUIRED>
<!ELEMENT streams (stream*)>
<!ELEMENT stream (categories,streamer,viewers_users)>
<!ELEMENT categories (category+)>
<!ELEMENT category (category_name,trending_rank)>
<!ELEMENT category_name (#PCDATA)>
<!ELEMENT trending_rank (#PCDATA)>
<!ATTLIST category id CDATA #REQUIRED>
<!ELEMENT streamer (stm:username,stm:viewers,stm:language,stm:subscriptions,stm:tags,stm:url)>
<!ELEMENT stm:username (#PCDATA)>
<!ELEMENT stm:viewers (#PCDATA)>
<!ELEMENT stm:language (#PCDATA)>
<!ELEMENT stm:subscriptions (#PCDATA)>
<!ELEMENT stm:tags (stm:tag+)>
<!ELEMENT stm:tag (#PCDATA)>
<!ELEMENT stm:url (#PCDATA)>
<!ELEMENT viewers_users (user*)>
<!ELEMENT user (usr:username,usr:last_message?,usr:language,usr:sub_chanels)>
<!ELEMENT usr:username (#PCDATA)>
<!ELEMENT usr:last_message (#PCDATA)>
<!ELEMENT usr:language (#PCDATA)>
<!ELEMENT usr:sub_chanels (usr:sub_chanel*)>
<!ELEMENT usr:sub_chanel (#PCDATA)>

=== AncorGG/Twitch_Assignment/twitch.xml
<!DOCTYPE twitch SYSTEM "twitch.dtd">
<twitch xmlns:stm="https://www.twitch.tv/streamer_username/"  xmlns:usr="https://www.twitch.tv/username/">
    <streams>
        <stream>
            <categories>
                <category id="2051613">
                    <category_name>Pokemon Fire Red</category_name>
                    <trending_rank>60</trending_rank>
                </category>
                <category id="2512343">
                    <category_name>Just Chatting</category_name>
                    <trending_rank>2</trending_rank>
                </category>
            </categories>
            <streamer>
                <stm:username>Arkevp</stm:username>
                <stm:viewers>7.2k</stm:viewers>
                <stm:language>Espa√±ol</stm:language>
                <stm:subscriptions>20</stm:subscriptions>
                <stm:tags>
                    <stm:tag>Art</stm:tag>
                </stm:tags>
                <stm:url>https://www.twitch.tv/Arkevp/</stm:url>
            </streamer>
            <viewers_users>
                <user>
                    <usr:username>Miova</usr:username>
                    <usr:last_message>Hello world!</usr:last_message>
                    <usr:language>Spanish</usr:language>
                    <usr:sub_chanels>
                        <usr:sub_chanel>Arkevp</usr:sub_chanel>
                    </usr:sub_chanels>
                </user>
                <user>
                    <usr:username>Erizomovil</usr:username>
                    <usr:last_message>Hell! Hell!</usr:last_message>
                    <usr:language>English</usr:language>
                    <usr:sub_chanels>
                        <usr:sub_chanel>Arkevp</usr:sub_chanel>
                    </usr:sub_chanels>
                </user>
            </viewers_users>
        </stream>
    </streams>
</twitch>
